version: '3.9'

services:
  xprofiler-console:
    image: cynosure/xprofiler-console:1.0.0
    ports:
      - 7443:7443
    env_file:
      - .env
    networks: 
      - ezm-network
    restart: always
    container_name: xprofiler-console
    depends_on: 
      - db
      - redis
    
  xtransit-manager:
    image: cynosure/xtransit-manager:1.0.0
    # ports:
    #   - 7543:7543
    env_file:
      - .env
    networks:
      - ezm-network
    restart: always
    container_name: xtransit-manager
    depends_on: 
      - db
      - redis

  xtransit-server:
    image: cynosure/xtransit-server:1.0.0
    environment: 
      - XTRANSIT_MANAGER_URL
    ports: 
      - 9090:9090
    networks: 
      - ezm-network
    restart: always
    container_name: xtransit-server
    depends_on: 
      - xtransit-manager

  redis:
    image: redis:6.2.4-alpine
    # ports:
    #   - 6379:6379
    networks:
      - ezm-network
    restart: always
    container_name: ezm-redis

  db:
    image: mysql:8.0.25
    # ports:
    #   - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data/db:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/sql:/opt/sql
    environment: 
      MYSQL_ROOT_PASSWORD: root
    networks:
      - ezm-network
    restart: always
    container_name: ezm-mysql

networks:
  ezm-network:
    external: 
      name: ezm-network